version: "3"
services:
  nodered:
    image: "nodered/node-red"
    ports:
      - "1880:1880"
    volumes:
      - c:\Users\MACIEJMARTUSEWICZ\NRdata:/data
    environment:
      DB_NAME: db
      DB_URL: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db?replicaSet=devrs
      DB_COLLECTION: LicencePlate
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - internal_network
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.0.4
    volumes:
      - ./data1/db:/data/db
      - ./data1/configdb:/data/configdb
    networks:
      - internal_network
    expose:
      - 27017
    ports:
      - 30001:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.0.4
    volumes:
      - ./data2/db:/data/db
      - ./data2/configdb:/data/configdb
    networks:
      - internal_network
    expose:
      - 27017
    ports:
      - 30002:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs" ]
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.0.4
    volumes:
      - ./data3/db:/data/db
      - ./data3/configdb:/data/configdb
    networks:
      - internal_network
    expose:
      - 27017
    ports:
      - 30003:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs" ]
networks:
  internal_network:
    driver: bridge
volumes:
  redis_data_container: