version: '3'
services:
  nodered:
    image: "nodered/node-red:latest-14"
    ports:
      - "1880:1880"
    volumes:
      - C:\Users\MACIEJMARTUSEWICZ\NRdata:/data
networks: 
  default: 
    external: 
      name: external-network
  
  
# docker network create external-network
# docker compose up -d
# docker compose down
# docker compose start
# docker compose stop