version: "3"
services:
  nodered:
    image: "nodered/node-red"
    ports:
      - "1880:1880"
    volumes:
      - c:\Users\MACIEJMARTUSEWICZ\NRdata:/data
    environment:
      MQTT_URL: mqtt
    depends_on:
      - mqtt
    networks:
      - internal_network
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883"
      - "9001"
    networks:
      - internal_network
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - mosquitto-conf:/mosquitto/config
networks:
  internal_network:
volumes:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
# docker-compose up -d
# docker-compose down
# docker-compose start
# docker-compose stop
