services:
  frontend:
    container_name: frontend
    image: nginx:alpine-slim
    ports:
      - "81:80"
    volumes:
      - './WebPostgREST:/usr/share/nginx/html'
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres
    networks:
      - private
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PGRST_OPENAPI_SERVER_PROXY_URI=${REST_HOST}
      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
    depends_on:
      - postgres
    networks:
      - private
    restart: always
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      - API_URL=${REST_HOST}
      - SWAGGER_JSON = /swagger.json
    depends_on:
      - postgrest
    restart: always
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - "./initdb:/docker-entrypoint-initdb.d"
    networks:
      - private
  admin-postgres:
    container_name: admin-postgres
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - private
volumes:
  postgres-data:
  pgadmin-data:
networks:
  private:
      driver: bridge

#    external: true
# docker-compose up -d
# docker-compose down
# docker-compose start
# docker-compose stop