version: "3"
services:
  json-server:
    image: "clue/json-server"
    ports:
      - "3000:80"
    volumes:
      - C:\Users\MACIEJMARTUSEWICZ\DockerData\jsonserver\db.json:/data/db.json
# docker-compose up -d
# docker-compose down
# docker-compose start
# docker-compose stop